apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: cka
spec: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodeport
  name: nodeport
  namespace: cka
spec:
  ports:
  - name: http
    nodePort: 31333
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: webhost
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvol1
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data1"
          
---      
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvclm1
  namespace: cka
spec:
  storageClassName: local-storage
  selector:
    matchLabels:
        type: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webhost
  name: webpod1
  namespace: cka
spec:
  volumes:
    - name: pvol1
      persistentVolumeClaim:
        claimName: pvclm1
  containers:
  - image: nginx
    name: webcon1
    ports:
    - containerPort: 80
      name: "http-server"
    volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: pvol1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
