apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvol1
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/k8snfs"
    server: 10.10.235.192
