apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvclm1
  namespace: ""
spec:
  storageClassName: local-storage
  selector:
    matchLabels:
        type: local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
