apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvclm1
  namespace: ""
spec:
  storageClassName: local-storage
  selector:
    matchLabels:
        type: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
