apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: matel-cm
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - {ip-start}-{ip-stop}
